name: app_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.51.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  get: 4.6.5
  http: ^0.13.4
  pluto_grid: ^4.0.0
  syncfusion_flutter_calendar: ^20.1.59
  transparent_image: ^2.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/sk-innovation-icon.png
